### PR TITLE
Language fixes in README

### PR DESCRIPTION
**Pull request by Atrate**
Signed-off-by: Atrate <Atrate@protonmail.com>

### CODE REVIEW

**Comment by stonega** [comment]
Sorry for my poor English, you are my hero, thanks！
Are you using the app?

**Comment by Atrate** [comment]
Yes, the app works very well and has a really good design. If I wanted to correct English strings inside the app, should I just change the file in `lib/I10n`?

**Comment by stonega** [comment]
> Yes, the app works very well and has a really good design. If I wanted to correct English strings inside the app, should I just change the file in `lib/I10n`?
So happy if you can help me about this, I am using a third platform to manage all translation work, can you send me you your email to send the invitation.

**Comment by Atrate** [comment]
Atrate@protonmail.com

**Comment by stonega** [comment]
@Atrate I have sent the invitation, you can active the account, and get all strings. 
Could you please join our telegram group? Want to have a discussion before change somrthing.
https://t.me/joinchat/Bk3LkRpTHy40QYC78PK7Qg

**Comment by Atrate** [comment]
> @Atrate I have sent the invitation, you can active the account, and get all strings.

Alright, thanks.

> Could you please join our telegram group? Want to have a discussion before change somrthing.

Unfortunately I do not use Telegram, I am available on Matrix, though.

**Comment by stonega** [comment]
> 
> Unfortunately I do not use Telegram, I am available on Matrix, though.
> 
I have just downloaded Element from fdroid, and signed up,   how can I found you?😀

**Comment by Atrate** [comment]
You'll find me as @atrate:matrix.org

**Comment by stonega** [comment]
> You'll find me as `@atrate:matrix.org`

I have sent you a message on matrix.

**Pull request merged**
